config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :projects
  get 'welcome/index'
  get 'posts/index'

  # root 'posts#index'
  root 'welcome#index'
end

app/models/post.rb
class Post < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged
end

app/models/project.rb
class Project < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show,:edit,:update,:destroy]
  def index
    @posts = Post.all.order("created_at DESC").paginate(page: params[:page], per_page: 2)
  end

  def new
    @post = Post.new
  end

  def create
    @post =Post.new(post_params)
    if @post.save
      redirect_to @post , notice: "Hey Vivek! Your Article was successfully saved!"
    else
      render 'new', notice: "Oh no,Vivek! I was unable to save your post"
    end
  end

  def show
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: "Hey! Your article successfuly saved!"
    else
      render 'new'
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end

  private

  def find_post
    @post = Post.friendly.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :body, :slug)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :find_project,only: [:show , :edit, :update, :destroy ]
  def index
    @projects = Project.all.order("created_at DESC").paginate(page: params[:page], per_page: 2)
  end

  def new
    @project =Project.new
  end

  def create
    @project = Project.new(project_param)
    if @project.save
      redirect_to @project ,notice: "Hey Vivek! You have successfuly created the project!"
    else
      render 'new' , notice: "Ohh No!Unable to save your project"
    end
  end

  def show
  end

  def edit

  end

  def update
    if @project.update(project_param)
      redirect_to @project, notice: "Hey! Your Project successfuly updated!"
    else
      render 'edit'
    end
  end

  def destroy
    @project.destroy
    redirect_to root_path
  end

  private

  def project_param
    params.require(:project).permit(:title,:description,:link,:slug)
    # params.require(:project).permit(:title,:description,:link)
  end
  def find_project
    @project =Project.friendly.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @posts = Post.all.limit(3).order("created_at DESC")
    @projects = Project.all.limit(3).order("created_at DESC")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  class HTMLwithPygments < Redcarpet::Render::HTML
    def block_code(code,language)
      Pygments.highlight(code, lexer: language)
    end
  end

  def markdown(content)
    renderer = HTMLwithPygments.new(hard_wrap: true, filter_html: true)
    options = {
      autolink: true,
      no_intra_emphasis: true,
      disable_indented_code_blocks: true,
      fenced_code_blocks: true,
      lax_html_blocks: true,
      strikethrough: true,
      superscript: true
    }
    Redcarpet::Markdown.new(renderer,options).render(content).html_safe
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
		<title> Vivek Designer-Part Designer,part developer</title>
		<link href='https://fonts.googleapis.com/css?family=Raleway:400,700' rel='stylesheet' type='text/css'>
		<!-- <link rel="stylesheet" href="font-awesome/css/font-awesome.min.css"> -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">

		<!-- <link rel="stylesheet" type="text/css" href="css/application.css"></link> -->
  		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  		<%= csrf_meta_tags %>
</head>
<body>
	<header id="main_navigation" class="clearfix">
			<!-- <a href="#" class="name">Vivek Gidmare</a> -->
			<%= link_to "Vivek Gidmare",root_path, class: "name"%>
			<nav>
				<!-- <a href="articles.html">Articles</a> -->
				<%= link_to "Articles", posts_path %>
				<!-- <a href="#">Projects</a> -->
				<%= link_to "Projects" , projects_path %>
				<a href="#">Contact</a>
			</nav>
	</header>
<!-- <%= link_to "New Post",new_post_path %> -->

	<%= yield %>

	<!-- footer -->
	<footer id="main_footer">
			<p class="copyright">&copy;2016 Vivek Gidmare</p>		
			<nav>
				<a href="https://twitter.com/bibekgi" target="_blank"><i class="fa fa-twitter" aria-hidden="true"></i>
</a>
				<a href="http://github.com/vivekgidmare" target="_blank"><i class="fa fa-github" aria-hidden="true"></i>
</a>
				<a href="http://facebook.com" target="_blank"><i class="fa fa-facebook" aria-hidden="true"></i>
</a>
			</nav>
		</footer>
</body>
</html>

app/views/posts/_discus.html.erb
<div id="disqus_thread"></div>
<script>

/**
 *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
 *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables */

var disqus_shortname = 'vblog';
var disqus_identifier= '<%= @post.id %>';
var disqus_title = '<%= @post.title %>';
var disqus_url ='<%= url_for([@post,{only_path: false}])%>';



var disqus_config = function () {
    this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
    this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};



(function() { // DON'T EDIT BELOW THIS LINE
    var d = document, s = d.createElement('script');
    s.src = '//vblog-1.disqus.com/embed.js';
    s.setAttribute('data-timestamp', +new Date());
    (d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
                                    

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>

 <% if @post.errors.any? %>	
  <h2> <%= pluralize(@post.errors.count,"error")%> prevented this from saving:</h2>
  		<ul>
  			<% @post.errors.full_messages.each do |msg| %>
  				<li> <%= msg %></li>
			<% end %>
  		</ul>
<% end %>
	  	
	  	<%= f.label :title %><br>
	  	<%= f.text_field :title %> 

	  	<br>
	  	<br>
	  	
	  	<%= f.label :body,"Write your article here" %><br>
	  	<%= f.text_area :body %>


	  	<br>
	  	<br>
	  	
	  	<%= f.submit %>
  	
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= render 'form' %>

app/views/posts/index.html.erb
<!-- Body -->
<h1 class="page_title">Stuff I've Written</h1>
<div id="posts_wrapper" class="skinny_wrapper">
	<!-- posts -->
<% @posts.each do |post| %>
	<div class="post">
		<p class="date"><%= post.created_at.strftime("%A, %b %d") %></p>
		<h2 class="post_h"><%= link_to post.title, post %></a></h2>
		<!-- <div><%=  truncate(post.body, :length => 35) %></div>	 -->
		<%=  link_to "Read Post",post %>
		<hr class="post_hr">
		
	</div>
<% end %>


	

	

</div>
<%= will_paginate @posts %>
	<!-- <div class="pagination">
		<span class="previous_page diabled">Previous</span>
		<em class="current">1</em>
		<a class="second" href="#">2</a>
		<a class="next_page" href="#">Next</a>
	</div> -->

app/views/posts/new.html.erb
<div class="skinny_wrapper wrapper_padding">
<h1>New Post</h1>
<%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div id="post_show_content" class="skinny_wrapper wrapper_padding">
	<header class="ps_header">
		<p class="post_show_date"><%= @post.created_at.strftime("%A, %b %d") %></p>
		<h1 class="psh"><a href="#"><%= @post.title %></a></h1>
		<hr class="post_hr">
	</header>
	<div id="content">
		<p><%= markdown @post.body %>
		<br>
		<br>
		<hr>			
		
		<%= link_to "Edit Post",edit_post_path(@post), class: "button" %>

		<%= link_to "Delete ",post_path(@post),method: :delete, data: {confirm: "Are you sure you want to delete this article?"} ,class: "button"  %>
	</div>
	<hr>
	<!-- share box -->
	<div id="share_box">
		<p class="sb_p">Share</p>
		<a onclick="javascript:window.open('http://www.twitter.com/share?text= <%= @post.title %> by @bibekgi - &amp; url=<%= url_for([@post, {only_path:false}])%>','_blank','width=800,height=500,top=200,left=300');void(0);">
			<i class="fa fa-twitter" aria-hidden="true"></i>
		</a>
		<a href="http://facebook.com" target="_blank"><i class="fa fa-facebook" aria-hidden="true"></i>
		</a>
		<a href="http://google.com" target="_blank"><i class="fa fa-google-plus" aria-hidden="true"></i>
		</a>
	</div>
	<hr>
	 <%= render 'discus' %>
</div>

app/views/projects/_discus.html.erb
<div id="disqus_thread"></div>
<script>

/**
 *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
 *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables */

var disqus_shortname = 'vblog';
var disqus_identifier= '<%= @project.id %>';
var disqus_title = '<%= @project.title %>';
var disqus_url ='<%= url_for([@project,{only_path: false}])%>';



var disqus_config = function () {
    this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
    this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};



(function() { // DON'T EDIT BELOW THIS LINE
    var d = document, s = d.createElement('script');
    s.src = '//vblog-1.disqus.com/embed.js';
    s.setAttribute('data-timestamp', +new Date());
    (d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
                                    

app/views/projects/_form.html.erb
<%= form_for @project do |p| %>

 <% if @project.errors.any? %>	
  <h2> <%= pluralize(@project.errors.count,"error")%> prevented this from saving:</h2>
  		<ul>
  			<% @project.errors.full_messages.each do |msg| %>
  				<li> <%= msg %></li>
			<% end %>
  		</ul>
<% end %>
	  	
	  	<%= p.label :title %><br>
	  	<%= p.text_field :title %> 

	  	<br>
	  	<br>
	  	
	  	<%= p.label :description%><br>
	  	<%= p.text_area :description %>

		<br>
	  	<br>
	  	
	  	<%= p.label :link,"Enter link of project" %><br>
	  	<%= p.text_field :link %>


	  	<br>
	  	<br>
	  	
	  	<%= p.submit %>
  	
<% end %>

app/views/projects/edit.html.erb
<div class="skinny_wrapper wrapper_padding">
<h1>Edit Project</h1>
<%= render 'form' %>
</div>

app/views/projects/index.html.erb
<!-- Body -->
<h1 class="page_title">Stuff I've Built</h1>
<div id="posts_wrapper" class="skinny_wrapper">
<% @projects.each do |project| %>
	<div class="post">
		<p class="date"><%= project.created_at.strftime("%A, %b %d") %></p>
		<h2 class="post_h"><%= link_to project.title, project %></a></h2>
		<%=  link_to "Link",project %>
		<hr class="post_hr">
		
	</div>
<% end %>
</div>
<%= will_paginate @projects %>
	<!-- <div class="pagination">
		<span class="previous_page diabled">Previous</span>
		<em class="current">1</em>
		<a class="second" href="#">2</a>
		<a class="next_page" href="#">Next</a>
	</div> -->

app/views/projects/new.html.erb
<div class="skinny_wrapper wrapper_padding">
<h1>New Project</h1>
<%= render 'form' %>
</div>

app/views/projects/show.html.erb
<div id="post_show_content" class="skinny_wrapper wrapper_padding">
	<header class="ps_header">
		<p class="post_show_date"><%= @project.created_at.strftime("%A, %b %d") %></p>
		<h1 class="psh"><a href="#"><%= @project.title %></a></h1>
		<hr class="post_hr">
	</header>
	<div id="content">
			
			<p><%= markdown @project.description %>
		<br>
		<br>

		<div class="button_wrapper">
		<a href="<%= @project.link%>" class="project_button" target="_blank">Visit <%= @project.title %></a>
		</div>
		<hr>
		<%= link_to "Edit Project",edit_project_path(@project), class: "button" %>

		<%= link_to "Delete ",project_path(@project),method: :delete, data: {confirm: "Are you sure you want to delete this Project?"} ,class: "button"  %>
	</div>
	<hr>			
</div>

app/views/welcome/index.html.erb
<div class="wrapper wrapper_padding clearfix">

	<div class="col-1 about homepage_content">
			<h2>About</h2>
			<hr>
			<p>I'm a designer &amp; developer living in Bangalore,
				India</p>
				<p>By day I work as Android Dev/Designer at 
					<a href="#">Voonik,</a> by night I do learn new things mostly code.
				</p>	
				<p>You can find me speaking in 140 characters on
					Twitter, staring at cricket scrore, and sharing source code on github.</p>
				</div>

				<div class="col-2 homepage_content">
					<h2>Stuff I've Written</h2>
					<hr>
					<!-- loop through posts -->
					<% @posts.each do |post| %>
						<h3><a href="#"><%= link_to post.title, post %></a></h3>
						<p class="date"><%= post.created_at.strftime("%A , %b %d") %></p>						
					<% end %>
				</div>
				<div class="col-3 homepage_content">
					<h2>Stuff I've Built</h2>
					<hr>
					<% @projects.each do |project| %>
						<h3><a href="#"><%= link_to project.title, project %></a></h3>
						<p class="date"><%= project.created_at.strftime("%A , %b %d") %></p>						
					<% end %>
					<!-- <h3><a href="#">Unicasts</a></h3>
					<p class="date">Friday April 10th</p>
					<h3>Android Community</h3>
					<p class="date">Friday April 10th</p>
					<h3>12 in 12 challenge</h3>
					<p class="date">Friday April 10th</p> -->
	</div>
</div>